import type { Metadata } from "next";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Public_Sans } from "next/font/google";
import { Geist } from "next/font/google";
import { ApiData } from "./components/ApiData";

const publicSans = Public_Sans({
  subsets: ["latin"],
});

 
const geist = Geist({
  subsets: ['latin'],
})
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${publicSans.className}`}
      >
        <ApiData>

        {children}
        </ApiData>
      </body>
    </html>
  );
}
